<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kas_masuk_model extends CI_Model
{

    public $table = 'kas_masuk';
    public $id = 'id_km';
    public $jenis = 'jenis';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('tgl_km', $this->order);
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        $this->db->where($this->jenis, 'Masuk');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('jenis', $q);
        $this->db->where('jenis', 'Masuk');
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $masuk = 'Masuk';
        $this->db->order_by($this->id, $this->order);
        $this->db->like('cara_bayar', $q);
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        $this->db->where('jenis', $masuk);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function tampil_bayar()
    {
        $result = array();
        $this->db->select('*');
        $this->db->from('cara_bayar');
        return $this->db->get()->result_array();
    }
    public function total_masuk()
    {
        $this->db->select_sum('masuk');
        $this->db->where($this->jenis, 'Masuk');
        return $this->db->get($this->table)->row();
    }
    public function total_masuk_per($tgl1, $tgl2)
    {
        $this->db->select_sum('masuk');
        $this->db->where($this->jenis, 'Masuk');
        $this->db->where('tgl_km BETWEEN "' . $tgl1 . '" AND "' . $tgl2 . '"');
        // $this->db->where($this->jenis, 'Masuk');
        return $this->db->get($this->table)->row();
    }
}
// this->db->where('sell_date BETWEEN "' . date('Y-m-d', strtotime($start_date)) . '" and "' . date('Y-m-d', strtotime($end_date)) . '"');

/* End of file kas_masuk_model.php */
/* Location: ./application/models/kas_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-22 17:57:40 */
/* http://harviacode.com */