<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rekap_kas_model extends CI_Model
{

    public $table = 'kas_masuk';
    public $id = 'id_km';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_km', $q);
        $this->db->or_like('tgl_km', $q);
        $this->db->or_like('uraian_km', $q);
        $this->db->or_like('masuk', $q);
        $this->db->or_like('keluar', $q);
        $this->db->or_like('jenis', $q);
        $this->db->or_like('cara_bayar', $q);
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_km', $q);
        $this->db->or_like('tgl_km', $q);
        $this->db->or_like('uraian_km', $q);
        $this->db->or_like('masuk', $q);
        $this->db->or_like('keluar', $q);
        $this->db->or_like('jenis', $q);
        $this->db->or_like('cara_bayar', $q);
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function get_per($tgl1, $tgl2)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
        $this->db->where('tgl_km BETWEEN "' . $tgl1 . '" AND "' . $tgl2 . '"');
        // $this->db->where($this->jenis, 'Masuk' and 'tgl_km' BETWEEN' . $tgl1 . 'AND' . $tgl2);
        return $this->db->get($this->table)->result();
    }
}
// $this->db->where('sell_date BETWEEN "' . date('Y-m-d', strtotime($start_date)) . '" and "' . date('Y-m-d', strtotime($end_date)) . '"');

/* End of file Rekap_kas_masjid_model.php */
/* Location: ./application/models/Rekap_kas_masjid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-22 18:44:56 */
/* http://harviacode.com */