<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class SupportTickets_model extends CI_Model
{

	public $table = 'support_tickets';
	public $id = 'id_support_tickets';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->join('cara_bayar', 'cara_bayar.id_cara_bayar = kas_masuk.id_cara_bayar');
		$this->db->where($this->jenis, 'Keluar');
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL,$id_username)
	{
		$this->db->like('pesan_ticket', $q);
		$this->db->from($this->table);
		$this->db->join('users', 'users.id_username = support_tickets.create_user');
		$this->db->where('create_user', $id_username);
		return $this->db->count_all_results();
	}

	// get data with limit and search
	function get_limit_data($limit, $start = 0, $q = NULL,$id_username)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->or_like('pesan_ticket', $q);
		$this->db->where('create_user', $id_username);
		$this->db->limit($limit, $start);
		$this->db->join('users', 'users.id_username = support_tickets.create_user');
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}
	public function tampil_jenisTicket()
	{
		$result = array();
		$this->db->select('*');
		$this->db->from('m_jenis_ticket');
		return $this->db->get()->result_array();
	}
}

/* End of file Kas_masjid_model_keluar.php */
/* Location: ./application/models/Kas_masjid_model_keluar.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-22 18:09:46 */
/* http://harviacode.com */
