<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tagihan_model extends CI_Model
{

    public $table = 'tagihan';
    public $id = 'id_tagihan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // // get all
    // function get_all()
    // {
    //     $this->db->order_by($this->id, $this->order);
    //     return $this->db->get($this->table)->result();
    // }

    function get_by_id($id)
    {
        $this->db->join('pelanggan', 'pelanggan.id_pelanggan = tagihan.id_pelanggan');
        $this->db->join('paket', 'paket.id_paket = pelanggan.id_paket');
        $this->db->join('bulan', 'bulan.id_bulan = tagihan.bulan');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL, $Y)
    {
        $this->db->like('nama_pelanggan', $q);

        $this->db->from($this->table);
        $this->db->join('pelanggan', 'pelanggan.id_pelanggan = tagihan.id_pelanggan');
        $this->db->join('cabang', 'cabang.id_cabang = pelanggan.id_cabang');
        $this->db->where('tagihan.status_bayar', 'N');

        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $y)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nama_pelanggan', $q);
        $this->db->from('tagihan');
        $this->db->join('pelanggan', 'pelanggan.id_pelanggan = tagihan.id_pelanggan');
        $this->db->join('cabang', 'cabang.id_cabang = pelanggan.id_cabang');
        $this->db->join('paket', 'paket.id_paket = pelanggan.id_paket');
        $this->db->join('bulan', 'bulan.id_bulan = tagihan.bulan');
        $this->db->where('tagihan.status_bayar', 'N');
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // bayar data
    function bayar($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function edit_data($id)
    {
        $this->db->from('tagihan');
        $this->db->join('pelanggan', 'pelanggan.id_pelanggan = tagihan.id_pelanggan');
        $this->db->where('id_tagihan', $id);
        return $this->db->get()->row_array();
    }
    public function tampil_bulan()
    {
        $result = array();
        $this->db->select('*');
        $this->db->from('bulan');
        return $this->db->get()->result_array();
    }
    public function tampil_tahun()
    {
        $result = array();
        $this->db->select('*');
        $this->db->from('tahun');
        return $this->db->get()->result_array();
    }
    public function tampil_bayar()
    {
        $result = array();
        $this->db->select('*');
        $this->db->from('cara_bayar');
        return $this->db->get()->result_array();
    }
}

/* End of file Tagihan_model.php */
/* Location: ./application/models/kas_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-22 17:57:40 */
/* http://harviacode.com */